### ISSUE TITLE
Not able to send you a comment on your blog:https://blogs.msmvps.com/deborahk/angular-ngrx-getting-started-problem-solver/

### ISSUE THREAD

**Issue by HansS** [DeborahK/Angular-NgRx-GettingStarted#1]
Error: You have entered an incorrect reCAPTCHA value.
 Click the BACK button on your browser and try again.

my comment:
Hi Deborah,

Angular is not complete without NgRx.
Without saying the Angular Team (see ngconf 2018) is pushing NgRx.

I am very happy that you publish your intention on the 23. April which is my birthday.
I am sure you will create a very carefully crafted course!

Good luck
Hans

**Comment by DeborahK** [comment]
Yes, I am using a blog provided by the Microsoft MVP program. I don't have control over its setup and this has been broken for a long time.

And thank you so much for the kind wishes.
