### ISSUE TITLE
Errors after upgrading to Angular 8

### ISSUE THREAD

**Issue by aminhsz** [DeborahK/Angular-NgRx-GettingStarted#13]
Upgraded to Angular 8 (8.2.0), and getting following errors.  Rxjs and rxjs-compat versions are 6.0.0, and ngrx/store version is 8.2.0.  Please, help.

I also tried with rxjs 6.4.0, but that gives a few more errors for rxjs alongwith these erros.
I tried different solutions suggested for previous versions of Angular with no success, but didn't find any help for 8.

    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(17,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(18,68): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(27,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(28,152): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(45,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(46,123): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(56,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/ml_parser/ast.d.ts(57,187): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(25,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(26,65): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(34,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(35,123): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(46,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(47,194): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(73,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(74,268): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(89,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(90,345): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(97,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(98,100): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(125,12): error TS1110: Type expected.
    node_modules/@angular/compiler/src/render3/r3_ast.d.ts(130,44): error TS1110: Type expected.
    node_modules/@angular/core/core.d.ts(12341,86): error TS1110: Type expected.
    node_modules/@angular/core/core.d.ts(12341,92): error TS1005: '=' expected.
    node_modules/@angular/core/core.d.ts(12341,94): error TS1005: ')' expected.
    node_modules/@angular/core/core.d.ts(12341,95): error TS1128: Declaration or statement expected.
    node_modules/@angular/core/core.d.ts(12341,96): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/effects/src/actions.d.ts(7,103): error TS1005: ';' expected.
    node_modules/@ngrx/effects/src/actions.d.ts(7,150): error TS1005: '(' expected.
    node_modules/@ngrx/effects/src/actions.d.ts(32,106): error TS1005: '>' expected.
    node_modules/@ngrx/effects/src/actions.d.ts(32,158): error TS1005: ')' expected.
    node_modules/@ngrx/effects/src/actions.d.ts(32,162): error TS1005: ';' expected.
    node_modules/@ngrx/effects/src/actions.d.ts(32,163): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/effects/src/actions.d.ts(32,187): error TS1005: '(' expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(4,34): error TS1005: ';' expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(5,21): error TS1005: ';' expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(6,3): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(7,42): error TS1005: ';' expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(7,78): error TS1005: '(' expected.
    node_modules/@ngrx/effects/src/effect_creator.d.ts(7,98): error TS1005: '(' expected.
    node_modules/@ngrx/store/src/models.d.ts(7,39): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(7,67): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(7,76): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(7,79): error TS1109: Expression expected.
    node_modules/@ngrx/store/src/models.d.ts(7,95): error TS1005: '(' expected.
    node_modules/@ngrx/store/src/models.d.ts(8,12): error TS1005: ',' expected.
    node_modules/@ngrx/store/src/models.d.ts(9,3): error TS1005: ',' expected.
    node_modules/@ngrx/store/src/models.d.ts(9,10): error TS1005: ')' expected.
    node_modules/@ngrx/store/src/models.d.ts(35,49): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(37,3): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/store/src/models.d.ts(43,85): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(45,3): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/store/src/models.d.ts(45,64): error TS1005: '(' expected.
    node_modules/@ngrx/store/src/models.d.ts(46,59): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(48,3): error TS1128: Declaration or statement expected.
    node_modules/@ngrx/store/src/models.d.ts(57,43): error TS1005: ';' expected.
    node_modules/@ngrx/store/src/models.d.ts(57,67): error TS1005: '=' expected.
    node_modules/@ngrx/store/src/tokens.d.ts(19,83): error TS1005: '>' expected.
    node_modules/@ngrx/store/src/tokens.d.ts(19,126): error TS1109: Expression expected.
    node_modules/@ngrx/store/src/tokens.d.ts(23,69): error TS1005: '>' expected.
    node_modules/@ngrx/store/src/tokens.d.ts(23,112): error TS1109: Expression expected.
    node_modules/@ngrx/store/src/tokens.d.ts(28,79): error TS1005: '>' expected.
    node_modules/@ngrx/store/src/tokens.d.ts(28,120): error TS1109: Expression expected.

**Comment by DeborahK** [comment]
Updated the project files to Angular v8.

**Comment by Vladimarinescu** [comment]
> Updated the project files to Angular v8.

What do you mean by that? What was the issue? I have the same problems. 
**package.json versions:**
  

- "rxjs": "^6.5.3"

- "@angular/cli": "~8.3.20",

-  "@angular/compiler-cli": "~8.2.14",


Is a rxjs issue?

**Comment by DeborahK** [comment]
It means *I* updated the project files to Angular 8 so that you don't have to. (The original poster was attempting to update the project files to Angular 8 themselves.)

And no, the rxjs version is *not* in sync with the Angular version. There is no rxjs 8 at this time.

Are you using the code from this repository? Which project are you using? What error are you getting exactly?
