### ISSUE TITLE
CSS is missing

### ISSUE THREAD

**Issue by gaoyuan1223m** [DeborahK/Angular-NgRx-GettingStarted#14]
I just wonder why css 
<img width="414" alt="no_css" src="https://user-images.githubusercontent.com/40973672/65367902-75f34780-dc6b-11e9-9826-e54ca3d9c032.png">
is missing

**Comment by DeborahK** [comment]
Which repo demo folder are you using?

**Comment by gaoyuan1223m** [comment]
> Which repo demo folder are you using?

I used the first Repo, namely the demo0

**Comment by gaoyuan1223m** [comment]
> Which repo demo folder are you using?

I believe that It's my bad! I failed to install bootstrap, actually! I am so sorry about that!

BTW, I so love your course! I can't wait for your next ngrx course! ngrx in-depth would be needed!

THX
