### ISSUE TITLE
Add @ngrx/entities and @ngrx/schematics

### ISSUE THREAD

**Issue by HansS** [DeborahK/Angular-NgRx-GettingStarted#2]
#Since you are known as business application developer, I would suggest you add ngrx/entities.
Your course will add true and long lasting values if you add the CRUD support with the help of entities.

When using NgRx you have to write very much boilerplate code (see action creators). To avoid the fatigue of writing this boilerplate, I would suggest that you introduce ngrx/schematics to avoid to manually write this boilerplate!

**Comment by DeborahK** [comment]
Thank you so much for your suggestion. 

We were given 2-3 HOURS to do an introduction to NgRx ... that is not enough time for even the basics ... so we were able to push it to 4 hours, but even that will be a challenge. We do currently plan to mention that entities and schematics are available and what they are for ... but there is just not enough time to cover them.

Also, this course is a "Getting Started" and is not meant to cover every feature. The hope is that other courses will follow that focus on some of the more intermediate level techniques such as you suggest.
