### ISSUE TITLE
Can you please convert to the use of action, reducer and effect creaters

### ISSUE THREAD

**Issue by StephanHartmann** [DeborahK/Angular-NgRx-GettingStarted#22]
Hello,

I have build my own playground app based on your demos.
I converted my source to use createaction and createreducer functions,
but with createeffect I got stuck.

Can you please add a additional source (like APM-Demo6) where the new creators are used.
This will help me a lot.

best regards
Stephan

**Comment by duncanhunter** [comment]
Hi @StephanHartmann,

Deborah and I are meeting this week to discuss updating to use the new syntax. It takes time to update courses but we will get a branch up with an updated demo during the process.

Maybe you can share a link to your repo or respond on the forum with some code snippets and we can have a look.

**Comment by whoiscarlo** [comment]
Hey @duncanhunter, love the Plural Sight course. Any idea on when you guys will be able to update the course and the repo?

**Comment by DeborahK** [comment]
We are working on it now. Hope to have it done by the end of the month and published early July.

You can see the (in-progress) code we are working with in this branch:  https://github.com/DeborahK/Angular-NgRx-GettingStarted/tree/angular-v9-demo0-update

**Comment by DeborahK** [comment]
The course update was published last night. It brings both the code and the course to Angular v9 and implements action, reducer, and effect creators.

You can find the list of changes here:

https://app.pluralsight.com/library/courses/angular-ngrx-getting-started
