### ISSUE TITLE
Suggestion for a product list with server-side sorting, paging and search

### ISSUE THREAD

**Issue by 0xFACE** [DeborahK/Angular-NgRx-GettingStarted#28]
This is not issue ;-). 
Thank you for a great course.
I would love to see data flow (effects, reducer) for a product list with server-side sorting, paging and search.

**Comment by duncanhunter** [comment]
Glad you like the course.

Thanks for the suggestion it would be great to have this on the Pluralsight library. As this is already a huge course for a 'Getting Started' style it would likely fit into an advanced course. We plan to update this course soon and maybe later this year we there is time for an advanced version. No plans for it at the moment though.

**Comment by 0xFACE** [comment]
Thanks for the reply. 
I'm looking forward for new advanced course on Pluralsight ;-)
