### ISSUE TITLE
Angular 9

### ISSUE THREAD

**Issue by lundmikkel** [DeborahK/Angular-NgRx-GettingStarted#37]
I can see that the last commit was to update to Angular 8. Are there any plans to update to Angular 9? And are the changes significant? Anything to be aware of when using NgRx in Angular 9, when watching this course?

**Comment by duncanhunter** [comment]
We are in the middle of recording an update to v9 out in July.

You can see the wip branch here https://github.com/DeborahK/Angular-NgRx-GettingStarted/tree/angular-v9-demo0-update

The main changes are to use the new syntax for actions, reducers and effects but it is a syntax change and if you understand the pattern and library it is a simple update.

**Comment by lundmikkel** [comment]
Ah, very nice. So the course on Pluralsight will also be updated in July? Not just the code here, right?

**Comment by duncanhunter** [comment]
Yes, this includes Pluralsight content :)

**Comment by DeborahK** [comment]
The course update was published last night. It brings *both* the code and the course to Angular v9 and implements action, reducer, and effect creators.

You can find the list of changes here:

https://app.pluralsight.com/library/courses/angular-ngrx-getting-started

**Comment by lundmikkel** [comment]
Great, thanks!
