### ISSUE TITLE
On delete, check current product id matches deleted product

### ISSUE THREAD

**Issue by smanderson** [DeborahK/Angular-NgRx-GettingStarted#45]
In product.reducer.ts on ProductActions.deleteProductSuccess (line 143) the currentProductId is set to null. Given the user can still interact with the app before the delete is successful or fails, it might be best to check the currentProductId matches the deleted product before setting the currentProductId to null. Left as is, the experience can be a bit jarring. I appreciate in a more "real world" example it might best to stop user interaction and wait for response which falls outside the scope of these lessons.

I would raise a PR but I'm not sure what the etiquette is for such things. Apologies if there is a preferred forum to raise this.

Great tutorial on Pluralsight - thank you!

**Comment by duncanhunter** [comment]
Hi

Yeah, that is totally a jarring experience :) 

I agree with you in a more real-world example you would guard for this. I would love to accept a PR to fix it and you are kind to offer but we strive to keep the code and the video in sync. For this reason, I do not think we should change it until the next course update. I have made a note to address this when we do the next update.

No apologies needed here or the Pluralsight course forum is fine to raise issues and I am glad you enjoyed the course.

Here is the image of the experience with the time travel debugger for anyone wondering and listening in.

![image](https://user-images.githubusercontent.com/2058227/102754800-999ec380-43c1-11eb-96c6-556c4551af3f.png)
