### ISSUE TITLE
npm install fails - ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by RaviSankarRao** [DeborahK/Angular-NgRx-GettingStarted#53]
After cloning the reporsitory and navigating to APM-Demo0, the command `npm install` fails with below error

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: apm@0.0.0
npm ERR! Found: jasmine-core@3.5.0
npm ERR! node_modules/jasmine-core
npm ERR!   dev jasmine-core@"~3.5.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer jasmine-core@">=3.8" from karma-jasmine-html-reporter@1.7.0
npm ERR! node_modules/karma-jasmine-html-reporter
npm ERR!   dev karma-jasmine-html-reporter@"^1.4.2" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
```

After update the below 2 packages version, `npm install` worked fine
```
jasmine-core
karma-jasmine-html-reporter
```
to the versions as shown below

![npm install Error - Updated Packages](https://user-images.githubusercontent.com/12565630/143497711-c7bd403e-6f09-4ec6-a711-b21ae25e0c56.png)

Requesting to update the package.json for all folders. I tried to create a PR but looks like the repo is not open for that

**Comment by mathsusan** [comment]
Thank you for pointing out this issue - saved me some extra frustration

**Comment by fahrizal** [comment]
Thank you. I have this issue also

**Comment by duncanhunter** [comment]
Thanks @RaviSankarRao for pointing this out we have updated the versions and closed this issue.
